[pytest]
DJANGO_SETTINGS_MODULE = fapag_collecte_backend.settings
python_files = tests.py test_*.py *_tests.py

# Options de base
addopts = -v --tb=short --strict-markers --durations=10 --showlocals --color=yes -p no:warnings -ra

# Configuration des marqueurs
markers =
    slow: marque les tests lents
    integration: tests d'intégration
    unit: tests unitaires
    security: tests de sécurité
    api: tests d'API
    db: tests nécessitant une base de données
    payment: tests de paiement
    auth: tests d'authentification

# Configuration de la couverture de code
testpaths = tests
python_classes = Test* *Test *TestCase
python_functions = test_*
