# Generated by Django 5.2.5 on 2025-08-23 11:41

import collecte.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cagnotte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('objectif', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='cagnottes/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), collecte.models.validate_file_size, collecte.models.validate_image_mime])),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminée'), ('en_attente', 'En attente'), ('archivee', 'Archivée')], default='en_attente', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('admin', 'Administrateur')], default='utilisateur', max_length=20)),
                ('deux_facteurs_active', models.BooleanField(default=False)),
                ('activation_token', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('activation_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='collecte_utilisateur_set', related_query_name='utilisateur', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='collecte_utilisateur_set', related_query_name='utilisateur', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cagnotte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='collecte.cagnotte')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalParticipation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_participation', models.DateTimeField(blank=True, editable=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20)),
                ('recu_pdf', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf']), collecte.models.validate_file_size, collecte.models.validate_pdf_mime])),
                ('reference', models.CharField(db_index=True, default=collecte.models.generate_reference, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cagnotte', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collecte.cagnotte')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical participation',
                'verbose_name_plural': 'historical participations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_participation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20)),
                ('recu_pdf', models.FileField(blank=True, null=True, upload_to='recu_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf']), collecte.models.validate_file_size, collecte.models.validate_pdf_mime])),
                ('reference', models.CharField(default=collecte.models.generate_reference, max_length=100, unique=True)),
                ('cagnotte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='collecte.cagnotte')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reference_psp', models.CharField(db_index=True, max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussie', 'Réussie'), ('echouee', 'Échouée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('horodatage', models.DateTimeField(blank=True, editable=False)),
                ('provider_ref', models.CharField(db_index=True, help_text="Pour l'idempotence des webhooks", max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collecte.participation')),
            ],
            options={
                'verbose_name': 'historical transaction',
                'verbose_name_plural': 'historical transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_psp', models.CharField(db_index=True, max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussie', 'Réussie'), ('echouee', 'Échouée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('provider_ref', models.CharField(db_index=True, help_text="Pour l'idempotence des webhooks", max_length=100, unique=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='collecte.participation')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWebhookEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('signature', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('traite', 'Traité'), ('erreur', 'Erreur')], default='recu', max_length=20)),
                ('horodatage', models.DateTimeField(blank=True, editable=False)),
                ('ip_source', models.GenericIPAddressField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collecte.transaction')),
            ],
            options={
                'verbose_name': 'historical webhook event',
                'verbose_name_plural': 'historical webhook events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('signature', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('traite', 'Traité'), ('erreur', 'Erreur')], default='recu', max_length=20)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('ip_source', models.GenericIPAddressField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='collecte.transaction')),
            ],
        ),
    ]
