# Generated by Django 5.2.5 on 2025-08-30 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code de sauvegarde à 8 chiffres', max_length=10, unique=True)),
                ('used', models.BooleanField(default=False, help_text='Code déjà utilisé')),
                ('used_at', models.DateTimeField(blank=True, help_text="Date d'utilisation", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code de sauvegarde',
                'verbose_name_plural': 'Codes de sauvegarde',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('requires_2fa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'verbose_name_plural': 'Tentatives de connexion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'appareil (ex: iPhone, Android)", max_length=64)),
                ('key', models.CharField(help_text='Clé secrète TOTP', max_length=32, unique=True)),
                ('confirmed', models.BooleanField(default=False, help_text="Appareil confirmé par l'utilisateur")),
                ('last_used', models.DateTimeField(blank=True, help_text='Dernière utilisation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appareil TOTP',
                'verbose_name_plural': 'Appareils TOTP',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
