"""
Django settings for fapag_collecte_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

# Charger les variables d'environnement
load_dotenv()

# Configuration des chemins
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ===== CORE SETTINGS =====
# Load environment variables
ENV = os.environ.copy()

# Configuration de l'authentification
AUTH_USER_MODEL = 'collecte.CustomUser'

# Configuration de la journalisation
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'app.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'json',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'security.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'json',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'error.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'json',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file', 'error_file', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'collecte': {
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file', 'error_file'],
        'level': 'INFO',
    },
}

# Configuration du rate limiting
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_VIEW = 'fapag_collecte_backend.views.ratelimited_error'

# Configuration 2FA (désactivée temporairement)
# TWO_FACTOR_PATCH_ADMIN = False
# TWO_FACTOR_WEBAUTHN_RP_NAME = 'FAPAG Collecte'
# TWO_FACTOR_LOGIN_TIMEOUT = 300  # 5 minutes
# TWO_FACTOR_REMEMBER_COOKIE_AGE = 30 * 24 * 3600  # 30 jours
# TWO_FACTOR_OTP_TOTP_ISSUER = 'FAPAG Collecte'

# SECURITY WARNING: keep the secret key used in production secret!
if 'SECRET_KEY' not in ENV:
    raise ValueError("SECRET_KEY must be set in environment variables")
SECRET_KEY = ENV['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV.get('DEBUG', 'False').lower() == 'true'

# Feature flags
ENABLE_MAINTENANCE_MODE = ENV.get('ENABLE_MAINTENANCE_MODE', 'False').lower() == 'true'
ENABLE_SIGNUP = ENV.get('ENABLE_SIGNUP', 'True').lower() == 'true'
ENABLE_EMAIL_VERIFICATION = ENV.get('ENABLE_EMAIL_VERIFICATION', 'True').lower() == 'true'

# ===== SECURITY SETTINGS =====
# Host/domain names that this Django site can serve
ALLOWED_HOSTS = ENV.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF settings
CSRF_TRUSTED_ORIGINS = ENV.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',')
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_USE_SESSIONS = True

# Session settings
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = int(ENV.get('SESSION_COOKIE_AGE', '1209600'))  # 2 weeks
SESSION_SAVE_EVERY_REQUEST = True

# Security middleware settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Configuration de django-axes (verrouillage de compte)
AXES_FAILURE_LIMIT = 5  # Nombre d'essais avant verrouillage
AXES_COOLOFF_TIME = 1  # 1 heure de verrouillage
AXES_LOCKOUT_TEMPLATE = 'account_locked.html'
AXES_LOCKOUT_URL = '/locked-out/'
AXES_VERBOSE = True
AXES_RESET_ON_SUCCESS = True  # Réinitialiser le compteur après une connexion réussie

SECURE_HSTS_SECONDS = int(ENV.get('SECURE_HSTS_SECONDS', '31536000'))  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = ENV.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
SECURE_HSTS_PRELOAD = ENV.get('SECURE_HSTS_PRELOAD', 'True') == 'True'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_REFERRER_POLICY = ENV.get('SECURE_REFERRER_POLICY', 'same-origin')
SECURE_SSL_REDIRECT = ENV.get('SECURE_SSL_REDIRECT', 'True') == 'True' and not DEBUG
X_FRAME_OPTIONS = ENV.get('X_FRAME_OPTIONS', 'DENY')

# CORS settings
CORS_ALLOWED_ORIGINS = ENV.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
CORS_ALLOW_CREDENTIALS = True

# Configuration de la politique de sécurité du contenu (CSP) - Format pour django-csp >= 4.0
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ["'self'"],
        'script-src': ["'self'"],
        'style-src': ["'self'", "'unsafe-inline'"],
        'img-src': ["'self'", 'data:'],
        'font-src': ["'self'"],
        'connect-src': ["'self'"],
        'object-src': ["'none'"],
        'base-uri': ["'self'"],
        'form-action': ["'self'"],
        'frame-ancestors': ["'self'"],
        'upgrade-insecure-requests': '',
        'block-all-mixed-content': ''
    }
}

# Configuration de la politique de sécurité des en-têtes
SECURE_HSTS_SECONDS = 0  # Désactivé
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1209600  # 2 semaines en secondes
SESSION_SAVE_EVERY_REQUEST = True

# Configuration de la politique de sécurité des mots de passe
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuration de la politique de sécurité des mots de passe avancée
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Configuration de la politique de sécurité des sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 semaines en secondes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SAMESITE = 'Lax'  # ou 'Strict' pour plus de sécurité

# Configuration de la politique de sécurité des fichiers uploadés
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Configuration de la politique de sécurité des en-têtes HTTP
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Configuration de la politique de sécurité des clés de chiffrement
if 'SECRET_KEY' not in os.environ:
    raise ValueError("La clé secrète doit être définie dans les variables d'environnement")

# Configuration de la politique de sécurité des cookies
CSRF_USE_SESSIONS = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Configuration de la politique de sécurité des en-têtes HTTP
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
PERMISSIONS_POLICY = {
    'accelerometer': '()',
    'camera': '()',
    'geolocation': '()',
    'microphone': '()',
}

# Application definition

# Configuration du logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',  # Pour le verrouillage de compte
    # Apps tierces
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'two_factor',
    'two_factor.plugins.phonenumber',
    'django_celery_results',
    'django_celery_beat',
    # 'storages',  # Désactivé temporairement
    'drf_yasg',
    'django_extensions',
    'csp',
    'django_filters',
    # 'sslserver',  # Désactivé temporairement
    # App principale
    'collecte',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'two_factor.auth_backends.TwoFactorBackend',
]

# Configuration Swagger/OpenAPI
SWAGGER_SETTINGS = {
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
    'DEFAULT_INFO': 'fapag_collecte_backend.urls.schema_view',
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'REFETCH_SCHEMA_WITH_AUTH': True,
    'REFETCH_SCHEMA_ON_LOGOUT': True,
    'PERSIST_AUTH': True,
    'DEFAULT_MODEL_RENDERING': 'example',
    'DEFAULT_MODEL_DEPTH': 2,
}

# Configuration pour la documentation Redoc
REDOC_SETTINGS = {
    'LAZY_RENDERING': True,
    'HIDE_HOSTNAME': False,
    'EXPAND_DEFAULT_TAGS': False,
    'PATH_IN_MIDDLE': False,
    'HIDE_LOADING': False,
    'NATIVE_SCROLLBARS': False,
    'REQUIRED_PROPS_FIRST': True,
    'NO_LOGO': False,
    'DISPLAY_OPERATION_ID': False,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'fapag_collecte_backend.middleware.SecurityHeadersMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # Two-factor authentication
    'two_factor.middleware.threadlocals.ThreadLocals',
    'csp.middleware.CSPMiddleware',
    'axes.middleware.AxesMiddleware',  # Doit être le dernier
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_ratelimit.middleware.RatelimitMiddleware',
]

ROOT_URLCONF = 'fapag_collecte_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fapag_collecte_backend.wsgi.application'

# Configuration de la base de données Supabase
import dj_database_url

# Configuration de la base de données via DATABASE_URL
database_url = os.environ.get('DATABASE_URL')
if not database_url:
    raise ValueError("La variable d'environnement DATABASE_URL doit être définie")

DATABASES = {
    'default': dj_database_url.config(
        default=database_url,
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=True
    )
}

# Configuration spécifique à PostgreSQL
DATABASES['default']['OPTIONS'] = {
    'connect_timeout': 5,
    'options': '-c statement_timeout=15000ms',
    'sslmode': 'require',
    'client_encoding': 'UTF8',
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password hashers
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Session settings
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Login URL
LOGIN_URL = 'two_factor:login'
LOGIN_REDIRECT_URL = 'two_factor:profile'
TWO_FACTOR_PATCH_ADMIN = True
TWO_FACTOR_REMEMBER_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 jours
TWO_FACTOR_CALL_GATEWAY = 'two_factor.gateways.fake.Fake'
TWO_FACTOR_SMS_GATEWAY = 'two_factor.gateways.twilio.gateway.Twilio'
TWO_FACTOR_WEBAUTHN_RP_NAME = 'FAPAG Collecte'
TWO_FACTOR_WEBAUTHN_RP_ID = ENV.get('TWO_FACTOR_WEBAUTHN_RP_ID', 'localhost')

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ===== STATIC FILES & MEDIA =====
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (user uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Storage backends (S3 for production, local for development)
if not DEBUG and ENV.get('AWS_ACCESS_KEY_ID'):
    # S3 storage configuration
    AWS_ACCESS_KEY_ID = ENV.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = ENV.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = ENV.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = ENV.get('AWS_S3_REGION_NAME')
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    AWS_DEFAULT_ACL = ENV.get('AWS_DEFAULT_ACL', 'private')
    AWS_QUERYSTRING_AUTH = ENV.get('AWS_QUERYSTRING_AUTH', 'True') == 'True'
    
    # S3 static settings
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
    
    # S3 media settings
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
    
    # Cache control
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration de la base de données principale
# Les paramètres sont définis plus haut dans le fichier

# Configuration des répliques de lecture (optionnel)
if ENV.get('DB_REPLICA_HOST'):
    DATABASE_ROUTERS = ['collecte.routers.PrimaryReplicaRouter']

# ===== INTERNATIONALIZATION =====
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Localization
LANGUAGE_CODE = ENV.get('LANGUAGE_CODE', 'fr-fr')
TIME_ZONE = ENV.get('TIME_ZONE', 'Africa/Libreville')
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Languages we provide translations for
LANGUAGES = [
    ('fr', _('French')),
    ('en', _('English')),
]

# Path where Django looks for translation files
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# ===== STORAGE CONFIGURATION =====
# S3/MinIO Storage Configuration
if ENV.get('AWS_ACCESS_KEY_ID'):
    # S3 storage configuration
    AWS_ACCESS_KEY_ID = ENV.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = ENV.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = ENV.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = ENV.get('AWS_S3_REGION_NAME')
    AWS_S3_ENDPOINT_URL = ENV.get('AWS_S3_ENDPOINT_URL')
    AWS_S3_SIGNATURE_VERSION = ENV.get('AWS_S3_SIGNATURE_VERSION', 's3v4')
    AWS_DEFAULT_ACL = ENV.get('AWS_DEFAULT_ACL', 'private')
    AWS_QUERYSTRING_AUTH = ENV.get('AWS_QUERYSTRING_AUTH', 'True') == 'True'
    
    # S3 custom domain (if using CloudFront or similar)
    if ENV.get('AWS_S3_CUSTOM_DOMAIN'):
        AWS_S3_CUSTOM_DOMAIN = ENV.get('AWS_S3_CUSTOM_DOMAIN')
    
    # S3 static settings
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # S3 media settings
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # Cache control
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # 1 day
    }
    
    # Use custom domain for URLs if provided
    if 'AWS_S3_CUSTOM_DOMAIN' in locals():
        STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
    else:
        STATIC_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/static/"
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/"
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = True

# ===== DJANGO REST FRAMEWORK =====
REST_FRAMEWORK = {
    # Authentication
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    
    # Permissions
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    
    # Custom exception handler
    'EXCEPTION_HANDLER': 'fapag_collecte_backend.exceptions.custom_exception_handler',
    
    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    
    # Rendering & Parsing
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    
    # Throttling
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'webhooks': '60/min',
    },
    
    # Error handling
    'EXCEPTION_HANDLER': 'fapag_collecte_backend.exceptions.custom_exception_handler',
    'NON_FIELD_ERRORS_KEY': 'error',
    
    # Versioning
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1'],
    
    # Filtering
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# ===== JWT CONFIGURATION =====
from datetime import timedelta

SIMPLE_JWT = {
    # Token lifetimes
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(ENV.get('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', 15))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(ENV.get('JWT_REFRESH_TOKEN_LIFETIME_DAYS', 1))),
    'ROTATE_REFRESH_TOKENS': ENV.get('JWT_ROTATE_REFRESH_TOKENS', 'True').lower() == 'true',
    'BLACKLIST_AFTER_ROTATION': ENV.get('JWT_BLACKLIST_AFTER_ROTATION', 'True').lower() == 'true',
    'UPDATE_LAST_LOGIN': ENV.get('JWT_UPDATE_LAST_LOGIN', 'False').lower() == 'true',
    
    # Configuration de chiffrement
    'ALGORITHM': ENV.get('JWT_ALGORITHM', 'HS256'),
    'SIGNING_KEY': ENV.get('JWT_SIGNING_KEY', SECRET_KEY),
    'VERIFYING_KEY': ENV.get('JWT_VERIFYING_KEY', None),
    'AUDIENCE': ENV.get('JWT_AUDIENCE', None),
    'ISSUER': ENV.get('JWT_ISSUER', None),
    'JWK_URL': ENV.get('JWT_JWK_URL', None),
    'LEEWAY': int(ENV.get('JWT_LEEWAY', 0)),
    
    # En-têtes d'authentification
    'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    # Classes de tokens
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    # JWT ID
    'JTI_CLAIM': 'jti',
    
    # Tokens glissants (sliding tokens)
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=int(ENV.get('JWT_SLIDING_TOKEN_LIFETIME_MINUTES', 5))),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=int(ENV.get('JWT_SLIDING_REFRESH_LIFETIME_DAYS', 1))),
    
    # Custom authentication
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTHENTICATION_RULE': 'collecte.authentication.custom_authentication_rule',

}

# ===== CORS CONFIGURATION =====
# CORS Configuration
# Configuration sécurisée de CORS à partir des variables d'environnement
CORS_ALLOW_ALL_ORIGINS = ENV.get('CORS_ALLOW_ALL_ORIGINS', 'False').lower() == 'true'
CORS_ALLOW_CREDENTIALS = ENV.get('CORS_ALLOW_CREDENTIALS', 'True').lower() == 'true'
CORS_ALLOWED_ORIGINS = ENV.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
CSRF_TRUSTED_ORIGINS = ENV.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')

# Headers de sécurité supplémentaires
SECURE_REFERRER_POLICY = 'same-origin'
X_CONTENT_TYPE_OPTIONS = 'nosniff'
X_XSS_PROTECTION = '1; mode=block'

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ===== CSRF CONFIGURATION =====
CSRF_TRUSTED_ORIGINS = ENV.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
CSRF_COOKIE_HTTPONLY = ENV.get('CSRF_COOKIE_HTTPONLY', 'True').lower() == 'true'
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = ENV.get('CSRF_COOKIE_SAMESITE', 'Lax')
CSRF_USE_SESSIONS = ENV.get('CSRF_USE_SESSIONS', 'False').lower() == 'true'

# ===== CELERY CONFIGURATION =====
CELERY_BROKER_URL = ENV.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = ENV.get('CELERY_RESULT_BACKEND', 'django-db')
CELERY_ACCEPT_CONTENT = ['json', 'pickle']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 7  # 1 week
CELERY_TASK_ALWAYS_EAGER = ENV.get('CELERY_TASK_ALWAYS_EAGER', 'False').lower() == 'true'
CELERY_TASK_EAGER_PROPAGATES = True

# Celery Beat Configuration (for scheduled tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Task routing
CELERY_TASK_ROUTES = {
    'collecte.tasks.*': {'queue': 'collecte'},
    'payments.tasks.*': {'queue': 'payments'},
}

# Worker settings
CELERY_WORKER_CONCURRENCY = int(ENV.get('CELERY_WORKER_CONCURRENCY', 4))
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(ENV.get('CELERY_WORKER_MAX_TASKS_PER_CHILD', 100))
CELERY_WORKER_PREFETCH_MULTIPLIER = int(ENV.get('CELERY_WORKER_PREFETCH_MULTIPLIER', 1))

# Monitoring
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True

# ===== PAYMENT CONFIGURATION =====
# SingPay Settings
SINGPAY = {
    'CLIENT_ID': ENV.get('SINGPAY_CLIENT_ID', ''),
    'API_KEY': ENV.get('SINGPAY_API_KEY', ''),
    'SECRET': ENV.get('SINGPAY_SECRET', ''),
    'WEBHOOK_SECRET': ENV.get('SINGPAY_WEBHOOK_SECRET', ''),
    'BASE_URL': ENV.get('SINGPAY_BASE_URL', 'http://sandbox-api.singpay.com'),
    'RETURN_URL': ENV.get('SINGPAY_RETURN_URL', 'http://localhost:3000/singpay/success'),
    'CANCEL_URL': ENV.get('SINGPAY_CANCEL_URL', 'http://localhost:3000/singpay/cancel'),
    'TIMEOUT': int(ENV.get('SINGPAY_TIMEOUT', 30)),  # seconds
    'MAX_RETRIES': int(ENV.get('SINGPAY_MAX_RETRIES', 3)),
    'RETRY_DELAY': int(ENV.get('SINGPAY_RETRY_DELAY', 1)),  # seconds
}

# Webhook IP Whitelist (optional)
SINGPAY_WEBHOOK_IPS = ENV.get('SINGPAY_WEBHOOK_IPS', '').split(',') if ENV.get('SINGPAY_WEBHOOK_IPS') else []

# Payment Settings
PAYMENT_METHODS = {
    'MOBILE_MONEY': ENV.get('PAYMENT_MOBILE_MONEY_ENABLED', 'True').lower() == 'true',
    'CREDIT_CARD': ENV.get('PAYMENT_CREDIT_CARD_ENABLED', 'True').lower() == 'true',
    'BANK_TRANSFER': ENV.get('PAYMENT_BANK_TRANSFER_ENABLED', 'True').lower() == 'true',
}

# Transaction Settings
TRANSACTION_TIMEOUT = int(ENV.get('TRANSACTION_TIMEOUT', 3600))  # 1 hour
MAX_PAYMENT_ATTEMPTS = int(ENV.get('MAX_PAYMENT_ATTEMPTS', 3))
PAYMENT_WEBHOOK_URL = ENV.get('PAYMENT_WEBHOOK_URL', 'https://yourdomain.com/api/webhooks/payments/')

# Currency Settings
DEFAULT_CURRENCY = ENV.get('DEFAULT_CURRENCY', 'XAF')
SUPPORTED_CURRENCIES = ENV.get('SUPPORTED_CURRENCIES', 'XAF,EUR,USD').split(',')
CURRENCY_DECIMAL_PLACES = {
    'XAF': 0,  # 0 decimal places for XAF
    'EUR': 2,
    'USD': 2,
}

# Commission & Fees
PAYMENT_COMMISSION_RATE = float(ENV.get('PAYMENT_COMMISSION_RATE', '0.015'))  # 1.5% default
FIXED_TRANSACTION_FEE = float(ENV.get('FIXED_TRANSACTION_FEE', '100'))  # 100 XAF default
SINGPAY_ALLOWED_IPS = ENV.get('SINGPAY_ALLOWED_IPS', '').split(',') if ENV.get('SINGPAY_ALLOWED_IPS') else []

# ===== EMAIL CONFIGURATION =====
# Email Backend Configuration
EMAIL_BACKEND = ENV.get(
    'EMAIL_BACKEND', 
    'django.core.mail.backends.console.EmailBackend' if DEBUG 
    else 'django.core.mail.backends.smtp.EmailBackend'
)

# SMTP Configuration
EMAIL_HOST = ENV.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(ENV.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = ENV.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = ENV.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = ENV.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = ENV.get('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_TIMEOUT = int(ENV.get('EMAIL_TIMEOUT', 30))  # seconds

# Email Settings
DEFAULT_FROM_EMAIL = ENV.get('DEFAULT_FROM_EMAIL', 'noreply@example.com')
SERVER_EMAIL = ENV.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = ENV.get('EMAIL_SUBJECT_PREFIX', '[FAPAG] ')

# Email Templates
EMAIL_TEMPLATES = {
    'WELCOME': 'emails/welcome.html',
    'PASSWORD_RESET': 'emails/password_reset.html',
    'PAYMENT_CONFIRMATION': 'emails/payment_confirmation.html',
    'CONTACT_FORM': 'emails/contact_form.html',
}

# Email Queue
EMAIL_QUEUE_ENABLED = ENV.get('EMAIL_QUEUE_ENABLED', 'True').lower() == 'true'
EMAIL_QUEUE_DELAY = int(ENV.get('EMAIL_QUEUE_DELAY', 5))  # seconds

# Email Testing
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')
    os.makedirs(EMAIL_FILE_PATH, exist_ok=True)

# ===== SECURITY CONFIGURATION =====
# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
REFERRER_POLICY = 'same-origin'
PERMISSIONS_POLICY = {
    'accelerometer': '()',
    'camera': '()',
    'geolocation': '()',
    'microphone': '()',
    'usb': '()',
}

# HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = int(ENV.get('SECURE_HSTS_SECONDS', '31536000'))  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = ENV.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() == 'true'
SECURE_HSTS_PRELOAD = ENV.get('SECURE_HSTS_PRELOAD', 'True').lower() == 'true'

# SSL/HTTPS
SECURE_SSL_REDIRECT = ENV.get('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_REDIRECT_EXEMPT = [r'^-']  # Don't redirect URLs starting with a dash

# Session Security
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Password Validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email', 'first_name', 'last_name'),
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Rate Limiting & Brute Force Protection
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # en heures
AXES_RESET_ON_SUCCESS = True
# Configuration recommandée pour django-axes 8.0+
AXES_HANDLER = 'axes.handlers.database.AxesDatabaseHandler'
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username", "user_agent"]

# Security Middleware
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# SameSite cookies pour limiter le CSRF cross-site
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
X_FRAME_OPTIONS = 'DENY'
# Réduire la fuite du referer
SECURE_REFERRER_POLICY = 'same-origin'
# Si derrière un proxy/ALB qui ajoute X-Forwarded-Proto
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Configuration CSP avancée - Toutes les directives sont maintenant dans CONTENT_SECURITY_POLICY

# Rate limiting
RATELIMIT_VIEW = 'collecte.views.ratelimited_error'
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'

# Production guard: extra hardening when DEBUG is False
IS_PROD = not DEBUG
if IS_PROD:
    # Ensure HTTPS everywhere and correct proxy behavior (e.g., AWS ALB)
    SECURE_SSL_REDIRECT = True
    USE_X_FORWARDED_HOST = True
    
    # Additional modern secure headers
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
    SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'
    
    # Auto-fill CSRF_TRUSTED_ORIGINS from ALLOWED_HOSTS if not provided explicitly
    if not CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS = [
            f"https://{host}"
            for host in ALLOWED_HOSTS
            if host not in ('localhost', '127.0.0.1')
        ]

# Logging & audit
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

AUTH_USER_MODEL = 'collecte.Utilisateur'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'axes.backends.AxesStandaloneBackend',
]

SWAGGER_USE_COMPAT_RENDERERS = False

# En développement, permettre tous les hôtes si DEBUG est True
if DEBUG:
    ALLOWED_HOSTS = ['*']
    import socket
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]


# Désactiver CSP pour les migrations
import sys
if 'migrate' in sys.argv:
    MIDDLEWARE = [m for m in MIDDLEWARE if not m.startswith('csp.middleware')]